name: Android Build

on:
  push:
    branches: [ \main\ ]
  pull_request:
    branches: [ \main\ ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install and Force Gradle 8.5
      run: |
        wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
        unzip -q gradle-8.5-bin.zip
        sudo mv gradle-8.5 /opt/gradle

    - name: Build with Absolute Gradle 8.5 Path
      run: /opt/gradle/bin/gradle assembleDebug
